# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-180845434-1'


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/vendexis-stan'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/shychan/'}
- {icon: 'envelope', link: 'mailto:info@vendex.is'}


# Customize site text
title: "Vendexis | Supercharging Unattended Retail"
header: "vendexis"
